#!/usr/bin/env ruby
require_relative 'lib/all'

# Assertions for script prerequisites
major, minor, patch  = RUBY_VERSION.split(".").map { |x| x.to_i }
raise "ERROR: Ruby Major Version must be == 2! - currently #{RUBY_VERSION}. Please update your MacOS." if major != 2
raise "ERROR: git is missing! Please run `xcode-select --install`" if `which git`.empty?

# Install Homebrew
brew.provision

# Update formulas
brew.update

# Upgrade existing packages
brew.upgrade

# Common dependencies
brew.install 'imagemagick'
# brew.install 'gcc' # contains gfortran, which is required for SciPy, R
brew.install 'openssl'

# Useful Utils
brew.install 'git' # source control
brew.install 'grep' # gnu grep is better than bsd grep on the MacOS
brew.install 'htop' # view system stats
brew.install 'jq' # JSON utility
brew.install 'tmux' # terminal multiplexer
brew.install 'vim' # text editor

# git.config('core.editor', '/opt/homebrew/bin/vim')

# Python
brew.install 'pyenv' # python version manager
pyenv.install('3.13.2')
pyenv.global('3.13.2')

# Ruby
brew.install 'rbenv' # ruby version manager
brew.install 'ruby-build' # ruby installer
rbenv.install('3.4.1')
rbenv.global('3.4.1')

# Node/Yarn
brew.install 'nodenv' # node version manager
brew.install 'node-build' # node installer
nodenv.install('22.13.1')
nodenv.global('22.13.1')
brew.install 'yarn'  # node package manager

# Java & Scala
brew.cask_install 'temurin@21' # OpenJDK 21
brew.install 'scala' # Scala Repl
brew.install 'sbt' # Java/Scala build tool
brew.cask_install 'visualvm' # JVM profiler

# Ohter useful applications
brew.cask_install 'keepingyouawake' # Keep computer from sleeping

# Remove old versions
brew.cleanup

# Make zsh the default shell
zsh.provision
zsh.make_default

# Dotfiles
file_util.symlink('dotfiles/.vimrc', '~/.vimrc')
file_util.symlink('dotfiles/.zshrc', '~/.zshrc')
